### ISSUE TITLE
ValueError('need more than 1 value to unpack',) in windows

### ISSUE THREAD

**Issue by geojacobm6** [victor-o-silva/db_file_storage#18]
Not able to save files in windows environment.

ValueError('need more than 1 value to unpack',)
db_file_storage/storage.py in _get_storage_attributes, line 70

**Comment by MrxTee** [comment]
This is easily fixed add
"import os"
to the top and then change line 70 from
mimetype_field, filename) = name.split('/')
to
mimetype_field, filename) = name.split(os.sep)

**Comment by victor-o-silva** [comment]
@geojacobm6 and @MrxTee 
Unfortunately I can't test the lib in Windows or Mac at the moment.
After 54b920bef78cc176f1d3dd04a0c2a07c511dadeb and MrxTee's 34205bc818742374a531fe2126fd91dd355cb2c2, I believe that the problem should be fixed.

If possible, could you clone the repo and run `python manage.py test` inside the `demo_and_tests` directory so I can make sure the issue is fixed, please?

**Comment by geojacobm6** [comment]
Thanks, it is working now.
